### ISSUE TITLE
Refunds not appearing in izettle dashboard

### ISSUE THREAD

**Issue by mmartinmendez** [iZettle/sdk-android#13]
# Expected Behavior

The refunds appear in the izettle dashboard.

# Current Behavior

The refund is successful but the transaction is not shown in the izettle dashboard.

## Context 

* Operating Version: Android version 9
* SDK version: 1.8.9

**Comment by fabriciovergara** [comment]
@dmilovanovi can you follow you this one please?

**Comment by mmartinmendez** [comment]
When logging the response from the sdk it says the refund was successful. To confirm i made the same refund a second time for which the response was that the refund was already performed. This is reflected with the refund appearing in the account in 2-3 days. The only part of the flow that is not working is the refund transaction/log not appearing in the dashboard when i sign into izettle. I use the sdk from ios as well and here the refund transaction logs appear immediately in the dashboard.

**Comment by said-iz** [comment]
Hello @mmartinmendez! Just to confirm, you don't see refunds in the iZettle Back Office (my.izettle.com) if you perform a refund through the iOS SDK?

**Comment by mmartinmendez** [comment]
Hi @said-iz,  I do see it through the ios sdk. I dont see it when i use the android sdk.

**Comment by said-iz** [comment]
@mmartinmendez thanks. We'll take a look and let you know 👍

**Comment by bobzettle** [comment]
Apologies for not getting back to you earlier. We have released a [fix](https://github.com/iZettle/sdk-android/releases/tag/release-1.14.13) for the reported issue, but would recommend you to update the SDK to the latest version.
You can view all the SDK releases [here](https://github.com/iZettle/sdk-android/releases).
Feel free to open a new case if the issue is still present or you require further assistance.
