### ISSUE TITLE
DatecsReaderV1 line 2 com.izettle.payments.android.readers.vendors.datecs.DatecsReaderV1.mutate$zettle_payments_sdk

### ISSUE THREAD

**Issue by RogerioNT** [iZettle/sdk-android#54]
# Expected Behavior

**This issue is intermittent, it happen after zettle return to our application on "onActivityResult"
then crash the app.**

# Current Behavior

What is the current behavior?

**unknown**

* Operating Version: Android 7.0
* SDK version: 1.25.0

**## Failure Logs**

Fatal Exception: com.izettle.payments.android.readers.vendors.datecs.DatecsReaderV1$UnexpectedActionForState
Action FailInstallment[fa29fcd5-8bcd-4712-b5de-7b899ab01ff0] is not supported in state Ready
com.izettle.payments.android.readers.vendors.datecs.DatecsReaderV1.mutate$zettle_payments_sdk (SourceFile:2)
com.izettle.payments.android.readers.vendors.datecs.DatecsReaderV1.reduce (SourceFile:338)
com.izettle.payments.android.readers.vendors.datecs.DatecsReaderV1.reduce$zettle_payments_sdk (SourceFile:30)
com.izettle.payments.android.readers.vendors.datecs.DatecsReaderV1$action$1.invoke (SourceFile:2)
com.izettle.payments.android.readers.vendors.datecs.DatecsReaderV1$action$1.invoke (SourceFile:1)
com.izettle.android.commons.state.StateImpl.update (SourceFile:7)
com.izettle.payments.android.readers.vendors.datecs.DatecsReaderV1.mutate$zettle_payments_sdk (SourceFile:1)
com.izettle.payments.android.readers.vendors.datecs.DatecsReaderV1.mutate$zettle_payments_sdk (SourceFile:28)
com.izettle.payments.android.payment.InstallmentManagerImpl$ReaderStateObserver$onWaitingForInstallment$1.invoke (SourceFile:2)
com.izettle.payments.android.payment.InstallmentManagerImpl$ReaderStateObserver$onWaitingForInstallment$1.invoke (SourceFile:1)
com.izettle.android.commons.thread.EventsLoopKt$sam$java_lang_Runnable$0.run (SourceFile)
android.os.Handler.handleCallback (Handler.java:836)

android.os.HandlerThread.run (HandlerThread.java:61)

**Comment by fabriciovergara** [comment]
@RogerioNT Just to confirm, it does happen when you get back to onActivityResult from a Payment or something else specific from your app?

**Comment by bobzettle** [comment]
Hi, since we haven't heard back during the last month we will be closing this issue now.
Feel free to reopen with new comments if needed.

**Comment by alexdpayne** [comment]
I'm seeing similar issues (but only 1-4 a day out of hundreds of successful transactions).

Since upgrading from 1.14.16 to 1.32.0
Android 8.1.0
Elo-i3-22Std

Various errors:

#com.izettle.payments.android.readers.vendors.datecs.ReaderV2Transport$RxConnection getRxConnection()
Action Request(2049, true) is not supported in state ConnectingToRx
Action Ready is not supported in state ConnectedToPw

#com.izettle.payments.android.readers.vendors.datecs.DatecsReaderV2
Command 0x7C0102000001007E is not expected in state Configured
Command 0x000482180006CA040000001244 is not expected in state TransactionConfirmedByReader
Command 0x0B01020000010009 is not expected in state TransactionInitializing
Command 0x000482180006CA04000000095F is not expected in state ConfigurationStarting

Due to the requirement to upgrade to this later version for the newer bluetooth modules, I can't go back to the working version.
Any help would be appreciated.
